---
configure_dotfiles: true
configure_terminal: true
configure_osx: true

configure_dock: true
dockitems_remove:
 - TV
 - Podcasts
 - 'App Store'
 - Calendar
 - Mail
 - Safari
 - Messages
 - Contacts
 - Notes
 - Maps
 - Photos
 - Reminders
 - FaceTime
 - Freeform
 - Music
 - TV

dockitems_persist:
 - name: "Google Chrome"
   path: "/Applications/Google Chrome.app/"
   pos: 3
 - name: "Discord Canary"
   path: "/Applications/Discord Canary.app/"
   pos: 4
 - name: "Warp"
   path: "/Applications/Warp.app/"
   pos: 5
 - name: "Visual Studio Code"
   path: "/Applications/Visual Studio Code.app/"
   pos: 6
 - name: "Bitwarden"
   path: "/Applications/Bitwarden.app/"
   pos: 7
 - name: "Spotify"
   path: "/Applications/Spotify.app/"
   pos: 8
 - name: "UTM"
   path: "/Applications/UTM.app/"
   pos: 9
 - name: "System Settings"
   path: "/Applications/System Settings.app/"
   pos: 10

configure_sudoers: false
sudoers_custom_config: ''

dotfiles_repo: https://github.com/azuanegrande/dotfiles-azu.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
#  - ansible  Installed via Pip.
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  - git
  - gh
  - go
  - gpg
  - iperf
  - libevent
  - nmap
  - node
  - nvm
  - php
  - pngpaste
  - readline
  - pv
  - wget
  - wrk
  - zsh-history-substring-search

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - google-chrome
  - handbrake
  - spotify
  - discord@canary
  - steam
  - warp
  - utm
  - tailscale
  - visual-studio-code
  - obs
  - transmission
  - bitwarden
  - git-credential-manager
  - mos
  - raycast
  - syncthing
  

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
#  - name: drush
#    state: present  present/absent, default: present
#    version: "^8.1"  default: N/A
gem_packages: []
#  - name: bundler
#    state: present  present/absent/latest, default: present
#    version: "~> 1.15.1"  default: N/A
npm_packages: []
#  - name: webpack
#    state: present  present/absent/latest, default: present
#    version: "^2.6"  default: N/A
pip_packages: []
#  - name: mkdocs
#    state: present  present/absent/latest, default: present
#    version: "0.16.3"  default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
